site_name: CitrixImagingTools
repo_url: https://github.com/megamorf/CitrixImagingTools
theme: readthedocs
pages:
- Home: index.md
- CitrixImagingTools Basics:
  - What is CitrixImagingTools: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md
